name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  check-clang:
    name: Check clang-format
    defaults:
      run:
        working-directory: ./package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "package/cpp"
          - "package/android/cpp"
          - "package/ios"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run clang-format style check
        uses: mrousavy/clang-format-action@v1
        with:
          clang-format-version: "16"
          check-path: ${{ matrix.path }}
          clang-format-style-path: package/cpp/.clang-format

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack

  android-debug:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Android
        run: cd example && npx react-native build-android --mode=debug

  android-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Android
        run: cd example && npx react-native build-android --mode=release

        # - name: Setup Java
        # uses: actions/setup-java@v3
        # with:
        #   distribution: "oracle"
        #   java-version: "17"

  ios-debug:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
          working-directory: ./package/example

      - name: Pod install
        run: pwd && cd example && bundle exec pod install

      - name: Build iOS
        run: cd example && npx react-native build-ios --configuration Debug
